var list = [["Edu","No","Turtle Academy","Programming","Basic Programming (Drag 'n drop)","4+","1-","0","Flash","TurtleAcademy","https://www.brainpop.com/games/turtleacademy/",,,true],
["Edu","No","Run Marco!","Programming","Basic Programming (Drag 'n drop)","4+","1","0","Web","RunMarko","https://www.brainpop.com/games/runmarco/",,,true],
["Edu","No","Blockly: Maze","Programming","Basic Programming (Drag 'n drop)","3+","1-","0","Web","BlocklyMaze","https://www.brainpop.com/games/blocklymaze/",,,true],
["Edu","Yes","Codecombat: Ogre Encounter","Programming","Basic Programming (Typing)","5+","Class","0","Web","CodeCombat","https://www.brainpop.com/games/codecombatogreencounter/",,,true],
["Edu","Maybe","Slice Fractions: School Edition","Math","Vaguely teaches fraction estimation","3-5","1-","0/$5","Flash","SliceFractions","https://www.brainpop.com/games/slicefractionsschooledition/",,,true],
["Edu","Yes","A Tangled Web","Math","Geometry (Contains serious math)","7+","2","0","Web","TangledWeb","https://www.brainpop.com/games/atangledweb/",,,true],
["Edu","Yes","Pyramid Panic","Math","Geometry (unreasonably difficult)","3+","1-","0","Flash","PyramidPanic","https://www.brainpop.com/games/pyramidpanic/",,,true],
["Edu","Maybe","Square Off","Math","Perimeter","3+","0.25-","0","Flash","SquareOff","https://www.brainpop.com/games/squareoff/",,,true],
["Edu","Maybe","Area Builder","Math","Perimeter and Area","3+","0.25-","0","Web","AreaBuilder","https://www.brainpop.com/games/areabuilder/",,,true],
["Edu","Yes","Balancing Act","Physics","Levers/Balances","4+","0.5-","0","Web","BalancingAct","https://www.brainpop.com/games/balancingact/",,,true],
["Edu","Maybe","Simple Machines Game","Physics","Levers, pulleys, wheels, inclined planes","3-8","0.25-","0","Flash","SimpleMachines","https://www.brainpop.com/games/simplemachinesgame/",,,true],
["Edu","Yes","Chronopticon","Astro-Physics","Astronomy: Phases of Sun, Moon, and constellations","5+","1-","0","Flash","Chronopticon","https://www.brainpop.com/games/chronopticon/",,,true],
["Edu","YES!","Kerbal Space Program","Astro-Physics","Orbital mechanics (EDU version also available)","9+","∞","$40","exe","KSP","https://www.humblebundle.com/store/kerbal-space-program",,,true],
["Edu","Yes","Lawcraft","Government","Getting a bill through the legislative branch","6+","1-","0","Flash","LawCraft","https://www.brainpop.com/games/lawcraft/",,,true],
["Edu","YES!","Ninja Kitchen","Misc.","Food prep safety","5+","1-","0","Flash","NinjaKitchen","https://www.brainpop.com/games/ninjakitchen/",,,true],
["Edu","Yes","Wave Combinator","Physics","Constructive and destructive wave interference","6+","0.5-","0","Web","WaveCombinator","https://www.brainpop.com/games/wavecombinator/",,,true],
["Edu","Yes","Wind Simulator","Physics","High and low pressure weather systems","4+","0.5-","0","Web","","https://www.brainpop.com/games/windsimulator/",,,true],
["Edu","Yes","Disaster Detector","Weather","Atmospheric measurements to predict disasters","5+","1","0","Flash","DisasterDetector","https://ssec.si.edu/disaster-detector",,,true],
["Edu","Yes","Hot Air Balloon","Physics","Buoyancy","3+","0.5-","0","Web","HotAirBalloon","https://www.brainpop.com/games/hotairballoon/",,,true],
["Edu","Yes","Magnethunt","Physics","Magnets and electromagnets","3+","0.75-","0","Web","MagnetHunt","https://www.brainpop.com/games/magnethunt/",,,true],
["Edu","Yes","The Electric Shocktopus","Physics","Magnets and magnetic fields","6+","2","0/$6","exe","Shocktopus","http://testtubegames.com/shocktopus.html",,,true],
["Edu","Yes","Velocity Raptor","Physics","Relativity and near light speed travel","9+","1","0","Web","VelocityRaptor","http://testtubegames.com/velocityraptor.html",,,true],
["Edu","Yes","Odyssey: The Invention of Science","Physics","Heliocentric/Geocentric models and related physics","4-10","5","$15","exe","Odyssey","http://store.steampowered.com/app/558110/Odyssey__The_Next_Generation_Science_Game/",,,true],
["Edu","YES!","Particulars","Physics","Subatomic particle mechanics","9+","7","$6","exe","Particulars","http://store.steampowered.com/app/259470/Particulars/",,,true],
["Edu","Yes","Quantum Marble Maze","Physics","Quantum mechanics","9+","1","0",".jar","QuantumMarbleMaze","http://tropic.org.uk/~crispin/quantum/",,,true],
["Edu","YES!","Bond Breaker 2.0","Physics","Atoms bonding","7+","2","0","Unity Web GL","BondBreaker","http://testtubegames.com/bondbreaker.html",,,true],
["Edu","No","One Man Band","Misc.","Very basic music mixing","0-4","0.25-","0","Flash","OneManBand","https://www.brainpop.com/games/onemanband/",,,true],
["Edu","No","Carmen Sandiago","Geography","Cities, their location, and a very brief history","varies","varies","0","DOS","CarmenSandiago","https://classicreload.com/where-in-the-world-is-carmen-sandiego-deluxe-edition.html ",,,true],
["Edu","Yes","Do I Have A Right?","Government","Bill of rights (best of this series)","","","0","Web","","https://www.brainpop.com/games/doihavearight/",,,true],
["Edu","Maybe","Court Quest","Government","Government: Court system of the US","6+","0.25","0","Flash","CourtQuest","https://www.brainpop.com/games/courtquest/",,,true],
["Edu","No","Win The White House","Government","Ideals of the Democratic and Republican parties","9+","0.5-","0","Web","WinWhiteHouse","https://www.brainpop.com/games/winthewhitehouse/",,,true],
["Edu","Maybe","Branches Of Power","Government","Pass a law through 3 branches of US federal government","4+","0.5-","0","Flash","BranchesOfPower","https://www.brainpop.com/games/branchesofpower/",,,true],
["Edu","NO!","Cast Your Vote","Government","Political personality test","0","0.25-","0","Flash","CastYourVote","https://www.brainpop.com/games/castyourvote/",,,true],
["Edu","Maybe","Executive Command","Government","Perform the duties of the president","3+","0.5-","0","Web","ExecutiveCommand","https://www.brainpop.com/games/executivecommand/",,,true],
["Edu","Yes","Immigration Nation","Government","Rules for immigrating to the US","3+","0.5-","0","Flash","ImmigrationNation","https://www.icivics.org/games/immigration-nation",,,true],
["Edu","No","We The Jury","Government","Act as a juror on a court case","","","0","Flash","","https://www.brainpop.com/games/wethejury/",,,true],
["Edu","Maybe","Argument Wars","History","Historic Supreme Court cases","","","0","Flash","","https://www.brainpop.com/games/argumentwars/",,,true],
["Edu","No","Activate","Government","Manage a social advocacy group","","","0","Flash","","https://www.brainpop.com/games/activate/",,,true],
["Edu","Maybe","Counties Work","Government","Bureaucracy","","","0","Web","","https://www.brainpop.com/games/countieswork/",,,true],
["Edu","Yes","People's Pie","Government","Federal Budget","","","0","Flash","PeoplesPie","https://www.brainpop.com/games/peoplespie/",,,true],
["Edu","Maybe","Represent Me","None","Stereotyping ","","","0","Flash","","https://www.brainpop.com/games/representme/",,,true],
["Edu","YES!","Sine Rider","Math","Graphing equations and equations graphs","6+","3","0","exe","","http://sineridergame.com/",,,true],
["Edu","No","Quations","Math","Just play Sine Rider","","1/4-","0","","","https://www.newgrounds.com/portal/view/680544",,,true],
["Edu","No","Supreme Decision","Government","How the Supreme court makes decisions","","","0","Flash","","https://www.brainpop.com/games/supremedecision/",,,true],
["Edu","Yes","Galactic Gloop Zoo","Physics","Heat transfer","","","0","Flash","","http://cct2.edc.org/rubyrealm/module4/bin/Module4.html",,,true],
["Edu","Yes","The Ruby Realm","Biology","Cellular processes","","","0","Flash","","http://cct2.edc.org/rubyrealm/bin/RubyRealmFlash.html",,,true],
["Edu","Maybe","Roboriot","Biology","Punnett squares","","","0","Flash","","http://cct2.edc.org/rubyrealm/roboriot2/bin/RoboRiot.html",,,true],
["Edu","Yes","Fuzzies","Biology","Punnett squares","","","0","","","https://www.newgrounds.com/portal/view/544333",,,true],
["Edu","Maybe","Immune Defense","Biology","Components of immune cells.","6+","2","0","Flash","ImmuneDefense","https://www.kongregate.com/games/DrAnn/immune-defense",,,true],
["Edu","Maybe","Cell Defense","Biology","Cell wall basics","6+","<0.5","0","Web","CellDefense","https://biomanbio.com/HTML5GamesandLabs/Cellgames/celldefensehtml5page.html",,,true],
["Edu","","Osy Osmosis","Biology","","","","$3","exe","","http://www.osyosmosis.com/",,,true],
["Edu","","Phylo: The DNA Puzzle Game","","","","","0","Web","","https://phylo.cs.mcgill.ca/#",,,true],
["Edu","No","Monster Music","None","Not a lot honestly (it's supposed to teach about electricity)","2+","","0","Flash","","http://cct2.edc.org/rubyrealm/monstermusic2/bin/MonsterMusic.html",,,true],
["Edu","Yes","Code Fred: Survival Mode","Biology","Human systems","4+","<0.5","0","Flash","CodeFred","https://www.brainpop.com/games/codefredsurvivalmode/",,,true],
["Edu","Yes","Cellcraft","Biology","Components in a cell","","","0","Flash","","https://www.kongregate.com/games/cellcraft/cellcraft",,,true],
["Edu","Yes","Ligand Quest","Biology","Ligands","","","0","exe","","https://artii.itch.io/ligandquest",,,true],
["Edu","Yes","Metablast","Biology","Microscopic tour of ?human? cells and systems","","","0","exe","","http://www.metablast.org/",,,true],
["Edu","No","Sepsis","Biology","Sepsis (a disease)","","<1/2","0","Flash","","http://www.newgrounds.com/portal/view/382253",,,true],
["Edu","Maybe","Life Preservers","Biology","Evolutionary Trees: very tutorial heavy","1+","<1/4","0","Unity Web","","https://www.brainpop.com/games/lifepreservers/",,,true],
["Edu","","Morphy!","","","","","0","ipad Only?","Morphy","https://ssec.si.edu/morphy",,,true],
["Edu","","Bacteria Combat","Biology","Don't know. IOS store won't admit it even exists.","8+","0","0/?","ipad Only?","BacteriaCombat","http://gamedrlimited.com/bacteria-combat",,,true],
["Edu","","SYNMOD Game ","Biology","Don't know. IOS store won't admit it even exists.","","","0","IOS","","https://www.biofaction.com/portfolio/synmod-game/",,,true],
["Edu","","Dragon Breeder","Biology","Genes and genotypes","8+","","0","Web","DragonBreeder","http://www.spongelab.com/interactives/dragon_breeder/index.cfm",,,true],
["Edu","Yes","Lost In Dutchland","Language","German Language","0+","","0","multi","","https://gamejolt.com/games/Lost_In_Deutschland/289399",,,true],
["Edu","No","Flap To The Future","Biology","Evolution","2+","<1/4","0","Web","","https://www.brainpop.com/games/flaptothefuture/",,,true],
["Edu","No","Immune Quest","Biology","Human immune cells","13+","2","0/$15","exe","","http://immunequest.com/",,,true],
["Edu","Yes","Mission Us: A Cheyenne Odyssey","History","Native Americans","5+","","0","Flash","","https://www.brainpop.com/games/missionusacheyenneodyssey/",,,true],
["Edu","Yes","Mission Us: City Of Immigrants","History","1820s life in NY as an immigrant","5+","","0","Flash","","https://www.brainpop.com/games/missionuscityofimmigrants/",,,true],
["Edu","Yes","Mission Us: Up From The Dust","History","The American Dust Bowl","5+","","0","Flash","","https://www.brainpop.com/games/missionusupfromthedust/",,,true],
["Edu","Maybe","Walden","Literature","Philosophy: Henry David Thoreau doing very little","7+","","0","","","https://gameinnovationlab.itch.io/walden",,,true],
["Edu","Yes","Food Chain Game","Biology","Food chain","","<1/4","0","Flash","","https://www.brainpop.com/games/foodchaingame/",,,true],
["Edu","No","Food Fight","Biology","Food chain: couldn't figure out how to play","","<1/4","0","Web","Exotrex","https://www.brainpop.com/games/foodfight/",,,true],
["Edu","No","Exotrex","","element symbols"," and identifying renewable and nonrenewable resources"," subatomic particles","$6","Web","","https://dig-itgames.com/portfolio/exotrex-game-science-space-grade8/",,,true],
["Edu","No","Exotrex2","","relative distances between planets and other celestial bodies",""," as well as Newton's third law","$6","Web","6-10","https://dig-itgames.com/portfolio/exotrex2-science-planetary_game/",,,true],
["Edu","Yes","Rational Redux","Math","Logic puzzles and proofs (propositional calculus)[Profanity]","6+","<1","0","Flash","RationalRedux","http://www.kongregate.com/games/tjubert/ir-rational-redux",,,true],
["Edu","NO!","Roman Town 2","History","Random mini-games intercut with Roman culture","","","$1","multi","RomanTown2","https://dig-itgames.com/portfolio/roman-town-2-social-studies-puzzles/",,,true],
["Edu","No","Brilliant.org","Many","What 2010 thought textbooks would be in 2020.","9+","∞","0/$25/m","Web","Brillian","Brilliant.org",,,true],
["Edu","","CK-12","Many","What 2020 textbooks should look like.","","","0","Web","","https://www.ck12.org/student/",,,true],
["Edu","No","The Sports Network 2","Job","Working at a news company","4+","","0","Flash","","https://www.brainpop.com/games/thesportsnetwork2/",,,true],
["Edu","Yes","Medmyst Animal Alert!","Job","Job as a pathologist","6+","","0","Flash","","https://www.brainpop.com/games/medmystanimalalert/",,,true],
["Edu","Yes","Quandary","Management","Making decisions based on public opinion","4+","","0","Web","","https://www.brainpop.com/games/quandary/",,,true],
["Edu","Yes","After The Storm: Day One","Job","Job at a modern newspaper","6+","","0","Web","","https://www.brainpop.com/games/afterthestormdayone/",,,true],
["Edu","No","Community In Crisis: Aftermath","Job","Running a community center","6+","","0","Web","","https://www.brainpop.com/games/communityincrisistheaftermath/",,,true],
["HW","NO!","Dino School Series","Math","Random school adjacent quizzes.","2+","2","0","Android","","https://play.google.com/store/apps/details?id=co.familyplay.dinograde5free",,,true],
["HW","NO!","_ Grade Learning Games Series","Many","Random games with quiz questions jammed in ","4+","2","0/$4","Android","SixthGradeLearningGames","https://play.google.com/store/apps/details?id=com.kevinbradford.games.sixthgrade",,,true],
["HW","Yes","Addition Blocks","Math","Math practice (addition) [Actually good]","1-4","","0","Web","","https://www.brainpop.com/games/additionblocks/",,,true],
["HW","Yes","Multiplication Blocks","Math","Math practice (multiplication) [Actually good]","2-4","","0","Web","","https://www.brainpop.com/games/multiplicationblocks/",,,true],
["HW","Yes","La Torre De Nozar","Math","Math practice (MATH PUNCHER!)","2-4","","0","exe","","https://sebagames.itch.io/la-torre-de-nozar",,,true],
["HW","Yes","Gate","Math","Math practice (addition and subtraction)","2-4","","0","Flash","","https://www.brainpop.com/games/gate/",,,true],
["HW","Maybe","Number Munchers","Math","Math practice (+ - x / primes)","1-4","","0","","","https://classicreload.com/number-munchers.html",,,true],
["HW","No","Lure Of The Labyrinth: Cafeteria","Math","Math practice (confusing)","","","0","Flash","","https://www.brainpop.com/games/lureofthelabyrinthemployeecafeteria/",,,true],
["HW","No","Math Blaster (Original)","Math","Math practice (confusing)","1-4","","0","","","https://classicreload.com/math-blaster-plus.html",,,true],
["HW","No","Math Blaster (Modern)","Math","Math practice and educational mini-games","0-4","","0","exe","","http://www.mathblaster.com/",,,true],
["HW","No","Lure Of The Labyrinth: Lounge","Math","Math practice (confusing)","","","0","Flash","","https://www.brainpop.com/games/lureofthelabyrinthemployeelounge/",,,true],
["HW","No","Lure Of The Labyrinth: Mine","Math","Math practice (confusing)","","","0","Flash","","https://www.brainpop.com/games/lureofthelabyrinthmineshaft/",,,true],
["HW","No","Number Jumble","Math","Math practice (very boring)","1-4","","0","Flash","","https://www.brainpop.com/games/numberjumble/",,,true],
["HW","Maybe","Primary Krypto","Math","Math practice (relatively complicated)","1-4","","0","Flash","","https://www.brainpop.com/games/primarykrypto/",,,true],
["HW","No","Teachley Mt. Multiplis","Math","Math practice (Visual multiplication)","","","0","Web","","https://www.brainpop.com/games/teachleymtmultiplis/",,,true],
["HW","No","Deep Sea Duel","Math","Math practice (addition)","1-4","","0","Flash","","https://www.brainpop.com/games/deepseaduel/",,,true],
["HW","Maybe","Addition Snowball Fight","Math","Math practice (addition)","1-4","","0","","","https://www.newgrounds.com/portal/view/489100",,,true],
["HW","No","Jelly Bean","Math","Math practice (addition and subtraction)","1-2","","0","Flash","","https://www.brainpop.com/games/jellybean/",,,true],
["HW","No","Riddlebooks","Math","Math practice / word problems (bad user interface)","2-4","","0","Flash","","https://www.brainpop.com/games/riddlebooks/",,,true],
["HW","No","Mathoria (Series)","Math","Math practice (RPG with math poorly replacing combat)","","","0","exe","","http://store.steampowered.com/app/434480/Mathoria_It_All_Adds_Up/",,,true],
["HW","No","Loot Pursuit: Pompeii","Math","Math practice (visual novel intercut with math problems)","2-6","","0/$4","IOS","LootPompeii","https://itunes.apple.com/us/app/loot-pursuit-pompeii/id853849610?mt=8",,,true],
["HW","Yes","Gi-Tract Chain Game","Biology","GI-Tract (learn parts of the digestive system)","4+","","0","","","https://www.newgrounds.com/portal/view/650397",,,true],
["HW","Maybe","Amino Acid Match Game","Biology","Human Amino Acids (test with no tutorial at all)","","","0","","","https://www.newgrounds.com/portal/view/631652",,,true],
["HW","Maybe","Glycolysis Match Game","Biology","Glycolysis (trial and error matching game)","","","0","","","https://www.athleticarcade.com/educational/match/glycolysis.html",,,true],
["HW","No","Ibiome-Wetland School Edition","Biology","Something about ecosystems???","","","0","Flash","","https://www.brainpop.com/games/ibiomewetlandschooledition/",,,true],
["HW","Maybe","Forgotten Island","Biology","A citizen science game about identifying bugs","4+",">2","0","Flash","Forgotten Island","https://citizensort.org/web.php/forgottenisland",,,true],
["HW","NO!","Knowledge Mine","Biology","Biology test with a game theme.","12+","2","0","Flash","KnowledgeMine","http://www.spongelab.com/interactives/km/",,,true],
["HW","No","Greek Alphabet Match Game","Literature","Greek Alphabet: trial and error matching game","","","0","","","https://www.athleticarcade.com/educational/match/greek-alphabet.html",,,true],
["HW","No","Adapted Mind - Math","Math","Homework for various types of math problems","1-6","","$10/m","Web","AdaptedMath","http://www.adaptedmind.com/Math-Worksheets.php",,,true],
["HW","NO!","Adapted Mind - Reading","Literature","Literature test prep","1-6","","0/$10/m","Web","AdaptedReading","http://www.adaptedmind.com/reading.php",,,true],
["HW","No","Production Line","Physics","What color metals burn","6+","<1/4","0","Web","ProductionLine","http://www.kongregate.com/games/ChrisM15/production-line",,,true],
["HW","Maybe","Bird Song Hero","Physics","Waveform/Sound association","4+","","0","Web","","https://www.brainpop.com/games/birdsonghero/",,,true],
["HW","No","Lost In Translation","Literature","French","0+","","0","exe","","https://mottomi.itch.io/lost-in-translation",,,true],
["HW","Maybe","Matter Sorter","Physics","Sort Solids, liquids, gases, and plasmas","","<1/4","0","Flash","","https://www.brainpop.com/games/mattersorter/",,,true],
["HW","No","Wuzzit Trouble","Math","Add and subtract by fixed values (difficult controls)","1-4","","0","Firefox","","https://www.brainpop.com/games/wuzzittrouble/",,,true],
["HW","Yes","Treefrog Treasure","Math","Fractions/Decimals practice (0 to 1)","1-4","","0","Flash","","https://www.brainpop.com/games/treefrogtreasure/",,,true],
["HW","Yes","Battleship Numberline","Math","Fractions/Decimals estimation practice","1-4","","0","Flash","","https://www.brainpop.com/games/battleshipnumberline/",,,true],
["HW","No","Dig It","Math","Fractions practice (0 to 9)","1-4","","0","Flash","","https://www.brainpop.com/games/digit/",,,true],
["HW","No","Drop Zone","Math","Fractions practice (adding to 1)","1-4","","0","Flash","","https://www.brainpop.com/games/dropzone/",,,true],
["HW","No","Flower Power","Math","Couldn't figure this one out","","","0","Web","","https://www.brainpop.com/games/flowerpower/",,,true],
["HW","No","Monster School Bus","Math","Adding to 10","1-2","","0","Flash","","https://www.brainpop.com/games/monsterschoolbus/",,,true],
["HW","No","Pearl Diver","Math","Number estimation and button mashing","","","0","Flash","","https://www.brainpop.com/games/pearldiver/",,,true],
["HW","No","Ratio Rumble","Math","Ratio practice","1-4","","0","Flash","","https://www.brainpop.com/games/ratiorumble/",,,true],
["HW","No","Branches Of Government Game","Government","3 US Federal Gov. Branches Test","","","0","Flash","","https://www.brainpop.com/games/branchesofgovernmentgame/",,,true],
["HW","No","Checks And Balances","Government","3 US Federal Gov. Branches Test","","","0","Flash","","https://www.brainpop.com/games/checksandbalances/",,,true],
["HW","No","Chef Solus' Build-A-Meal","Health","Create a day's worth of balanced meals","","","0","Flash","","https://www.brainpop.com/games/chefsolusbuildameal/",,,true],
["HW","No","Quill","Literature","You are an editor (very bland)","","","0","Flash","","https://www.brainpop.com/games/quill/",,,true],
["HW","Maybe","Oncology","Biology","How cancer is detected and treated","","","0","Flash","","https://www.brainpop.com/games/oncology/",,,true],
["HW","Maybe","Foldit","Physics","Folding proteins","9+","∞","0","exe","","https://fold.it/",,,true],
["HW","Yes","World Countries Quiz","Geography","Test names, capitals, or flags of world countries.","","","0","","","https://www.newgrounds.com/portal/view/629856",,,true],
["HW","No","Conquering Europe","Geography","Test names or cities of European countries","","","0","","","https://www.newgrounds.com/portal/view/625046",,,true],
["HW","No","Lord Of The Flies","Literature","Test for the book Lord of the Flies","","","0","Flash","","https://www.brainpop.com/games/lordoftheflies/",,,true],
["HW","No","Theoreum","Physics","Text dumps","","<1/4","0","exe","","https://misfitvillage.itch.io/theoreum",,,true],
["HW","Yes","Guts And Bolts","Biology","Human systems inputs and outputs","","","0","Web","","https://www.brainpop.com/games/gutsandbolts/",,,true],
["HW","Yes","Build-A-Body: Digestive System","Biology","Human Biology: drag 'n drop","","","0","Flash","","https://www.brainpop.com/games/buildabodydigestivesystem/",,,true],
["HW","Maybe","Organ Transplant 2","Biology","Human Biology: drag 'n drop","","","0","","","https://www.newgrounds.com/portal/view/600659",,,true],
["HW","No","Immune System Game","Biology","Human Biology: Fill in the blank","","","0","","","https://www.newgrounds.com/portal/view/478787",,,true],
["HW","Yes","Build-A-Tree","Biology","Tree Biology: drag 'n drop","","","0","Flash","","https://www.brainpop.com/games/buildatree/",,,true],
["HW","No","Sortify (Series)","Literature","Vocabulary (sorting by association)","","","0","Web","","https://www.brainpop.com/games/sortify/",,,true],
["HW","Maybe","Tynker (Series)","Programming","Basic programming (Drag 'n drop)","","","0","Flash","","https://www.brainpop.com/games/game-finder/?game_keyword=developer:%20Tynker",,,true],
["HW","No","Time Zone X (Series)","History","Historical timelines","","","0","Web","","https://www.brainpop.com/games/timezonex/",,,true],
["HW","No","The Meaning Of Beep (Series)","Literature","Vocabulary","","","0","Web","","https://www.brainpop.com/games/themeaningofbeep/",,,true],
["HW","No","Chemistry","Chemistry","Build Molecules","","<3/4","0","","","https://www.newgrounds.com/portal/view/635310",,,true],
["HW","Maybe","Circle Master 2","Physics","Gravity","4+","<0.5","0","Web","CircleMaster","http://www.kongregate.com/games/akane2002/circle-master-2-gravitation",,,true],
["HW","No","Solarium","Biology","A walking simulator / quiz game about plants.","6+","1","0","exe","Solarium","http://sunfleck.com/",,,true],
["Issue","No","This War Of Mine","Issue","The effects of war on civilians","","","$20","exe","","http://store.steampowered.com/app/282070/This_War_of_Mine/",,,true],
["Issue","Maybe","Invasion!!","Issue","Invasive species","","","0","Flash","","https://www.brainpop.com/games/invasion/",,,true],
["Issue","No","Sam And Nicole","Issue","Gay relationships","","","0","exe","","https://sigridsanglar.itch.io/sam-and-nicole-demo",,,true],
["Issue","No","Yaku International","Issue","Getting water in Africa","0+","0.5-","0","Web","YakuInternational","http://www.kongregate.com/games/MouseCity/yaku-international",,,true],
["Issue","Maybe","Super Energy Apocalypse","Issue","Waste management and pollution","","1","0","","SuperEnergyApocalypse","http://www.newgrounds.com/portal/view/430963",,,true],
["Issue","No","Aquation","Issue","Vague idea of the world's drinkable water supply system.","0+","0.25-","0","Web","Aquation","http://ssec.si.edu/sites/default/files/games/Aquation/index.html",,,true],
["Issue","No","SimCity Edu: Pollution Challenge","Issue","Pollution","3+","","","exe","","https://www.glasslabgames.org/games/SC",,,true],
["Issue","NO!","Digital Compass","Issue","morality (very vague and unhelpful) (propaganda)","2-4","","0","Flash","","https://www.brainpop.com/games/digitalcompass/",,,true],
["Sim","No","Ostevera","Government","Infrastructure management","3+","0.5-","0","Web","Ostevera","https://ostevera.spongelab.com/game/index.cfm",,,true],
["Sim","Yes","A Slower Speed of Light","Physics","3D game showing relativity","9+","","0","exe","","http://gamelab.mit.edu/games/a-slower-speed-of-light/",,,true],
["Sim","No","Build A Solar System","Astro-Physics","2D orbital mechanics sim","","<1/4","0","Flash","","https://www.brainpop.com/games/buildasolarsystem/",,,true],
["Sim","Yes","Color Vision","Physics","Light spectrum and vision","","<1/4","0","Web","","https://www.brainpop.com/games/colorvision/",,,true],
["Sim","Yes","Molecules And Light","Physics","Light interaction with particles","","<1/4","0","Web","","https://www.brainpop.com/games/moleculesandlight/",,,true],
["Sim","Yes","Phet Interactive Simulations","Physics","Many physics simulations","0+","a lot","0","Web","Phet","https://phet.colorado.edu/",,,true],
["Sim","","Explore Learning","Many","Many physics simulations","3+","a lot","","","","https://www.explorelearning.com/",,,true],
["Sim","","SimCityEDU","","","","","","","","https://www.glasslabgames.org/games/SC",,,true],
["Sim","No","The Fiscal Ship","Government","Balancing the US federal budget","","<1/4","0","Web","","https://www.brainpop.com/games/thefiscalship/",,,true],
["Sim","Yes","What Plants Need","Biology","Biological inputs of plants: Water, light, CO2","","<1/4","0","Flash","","https://www.brainpop.com/games/whatplantsneed/",,,true],
["Sim","No","Desalination","Physics","Desalinating water (I couldn't figure it out)","","<1/4","0","Flash","","https://www.brainpop.com/games/desalination/",,,true],
["Sim","Maybe","Cool Science Careers: Imagine Y.","Biology","Neuropsychology, toxicology, epidemiology, neurobiology","","","0","Flash","","https://www.brainpop.com/games/coolsciencecareersimagineyourself/",,,true],
["Sim","Yes","District","Government","Gerrymandering ","","","0","Web","","http://polytrope.com/district/",,,true],
["Sim","Yes","Parable Of The Polygons","Math","Statistics of population diversity","","<1/2","0","Web","","http://ncase.me/polygons/",,,true],
["Sim","No","American Revolution Timeline","History","American revolution timeline","","<1/4","0","Flash","","https://www.brainpop.com/games/americanrevolutiontimeline/",,,true],
["Sim","No","Pavlov's Dog","Misc.","Psychology: Pavlov's dog and that's it","","<1/4","0","Flash","","https://www.brainpop.com/games/pavlovsdog/",,,true],
["Sim","No","Concentration","Chemistry","Solution concentrations","","<1/4","0","Web","","https://www.brainpop.com/games/concentration/",,,true],
["Sim","Yes","Energy Skate Park: Basics","Physics","Energy = Potential + Kinetic + Friction losses","","<1/4","0","Web","","https://www.brainpop.com/games/energyskateparkbasics/",,,true],
["Sim","No","Graphing Lines","Math","Graphs","","<1/4","0","Web","","https://www.brainpop.com/games/graphinglines/",,,true],
["Sim","Maybe","Wave On A String","Physics","Waves","","<1/4","0","Web","","https://www.brainpop.com/games/waveonastring/",,,true],
["Sim","Maybe","Quantum Minigolf","Physics","Quantum mechanics (uncertainty)","","<1/4","0","exe","","http://quantumminigolf.sourceforge.net/",,,true],
["Sim","No","Sizing Up The Universe","Astro-Physics","Shows scale of planetary/universal bodies","","<1/4","0","Web","","https://www.brainpop.com/games/sizinguptheuniverse/",,,true],
["Sim","","Gravity Simulator","Physics","Gravity","6+","∞","0/$6","Web","GravitySimulator","http://testtubegames.com/gravity.html",,,true],
["Sim","Maybe","Universe Sandbox","Astro-Physics","Orbits and other planetary physics","","<1/4","$25","exe","","http://store.steampowered.com/app/230290/Universe_Sandbox/",,,true],
["Sim","No","Csi: Flight Adv. Forces Of Flight","Physics","Not a lot (Was obviously made for a museum)","","<1/4","0","Flash","","https://www.brainpop.com/games/csiflightadventuresforcesofflight/",,,true],
["Sim","No","Csi: Flight Adv. Flight School","Physics","Not a lot (Was obviously made for a museum)","","<1/4","0","Flash","","https://www.brainpop.com/games/csiflightadventuresflightschool/",,,true],
["Sim","No","Construct-A-Saurus","History","Dinosaurs (Was obviously made for a museum)","","<1/4","0","Flash","","https://www.brainpop.com/games/constructasaurus/",,,true],
["Sim","No","Stock Market Game","Misc.","Stock market game (exactly as boring as it sounds)","","<1/4","0","","","https://www.newgrounds.com/portal/view/410269",,,true],
["Sim","No","Sticky Outie Bits","Biology","Basic fish anatomy and artificial selection","","<1/4","0","","","https://www.newgrounds.com/portal/view/629919",,,true],
["Tool","Yes","Minecraftedu","None","It takes a skilled teacher to make this worth using.","0+","∞","???","exe","MinecraftEdu","https://education.minecraft.net/",,,true],
["Tool","","","Graphing","","","∞","0","Web","","https://www.geogebra.org/",,,true],
["Tool","","Desmos","Graphing","","","∞","0","Web","","https://www.desmos.com/",,,true],
["Video","No","Virtual Labs: U. Water Activity","Job","Water concentration in food affects shelf life","","<1/2","0","Flash","","https://www.brainpop.com/games/virtuallabsunderstandingwateractivity/",,,true],
["Video","No","Virtual Labs (Series)","Job","Brief overview of some jobs","","<1/2","0","Flash","","https://www.brainpop.com/games/game-finder/?game_keyword=developer:%20NMSU%20Learning%20Games%20Lab",,,true],
["Video","No","Drake Equation","Misc.","Watch www.youtube.com/watch?v=8YmiRfCDeNg instead","","<1/4","0","Flash","","https://www.brainpop.com/games/drakeequation/",,,true],
["Video","No","Close-Knit Neighbors","Biology","Ecosystems of microbes","","<1/4","0","Flash","","https://www.brainpop.com/games/closeknitneighbors/",,,true],
["Video","","Apollo 11 VR","History","Moon Landing","","","0","VR Game","","http://store.steampowered.com/app/457860/Apollo_11_VR/",,,true],
["Video","","Rentry","History","","","","","","","http://reentrygame.com/",,,true],
["Video","","Orbiter 2016","History","","","","0","","","http://orbit.medphys.ucl.ac.uk/",,,true],
["Video","","Titanic VR","History","Titanic","","","0","VR Game","","http://store.steampowered.com/app/741430/Titanic_VR/",,,true],
["Video","NO!","Operation Ebola!","Biology","Ebola Virus (slideshow with terrible game at the end)","9+","<0.25","0","Web","Ebola","https://catlilli.itch.io/ebola",,,true],
["Video","NO!","Space Simulator","Astro-Physics","Flight simulator for historical space flights.","4+","2?","$10","exe","SpaceSimulator","https://store.steampowered.com/app/529060/Space_Simulator/",,,true],
["Video","No","Powers of Minus Ten","Biology","Zoom in on cells to see them at different magnifications","6+","<1","$2","IOS","POMT","http://powersofminusten.com/",,,true],
["WorkBook","No","Excavate! Byzantine Education Game","History","An archaeologist looks at Byzantine culture","","","$4","multi","ExcavateByzantine","https://dig-itgames.com/portfolio/excavate-byzantine-social-studies-game/",,,true],
["WorkBook","No","Excavate! Mesopotamia","History","An archaeologist looks at Mesopotamian culture","","","$4","multi","ExcavateMesopotamia","https://dig-itgames.com/portfolio/excavate-mesopotamia-world-history-game-culture/#Mat",,,true],
["WorkBook","No","Excavate! Egypt","History","An archaeologist looks at Egyptian culture","","","$4","multi","ExcavateEgypt","https://dig-itgames.com/portfolio/excavate-egypt-world-history-lesson-game/",,,true],
["WorkBook","No","Excavate! Mesoamerica","History","An archaeologist looks at Mesoamerican culture","","","$4","multi","ExcavateMesoamerica","https://dig-itgames.com/portfolio/excavate-mesoamerica-inca-maya-history-game/",,,true],
["WorkBook","No","Excavate! Greece","History","An archaeologist looks at ancient Greek culture","","","$4","multi","ExcavateGreece","https://dig-itgames.com/portfolio/excavate-greece-world-history-greek/",,,true],
["WorkBook","No","Excavate! Rome","History","An archaeologist looks at ancient Roman culture","","","$4","multi","ExcavateRome","https://dig-itgames.com/portfolio/excavate-ancient-rome-social-studies/",,,true],
["WorkBook","No","Loot Pursuit: Early America","Math","Math practice (visual novel intercut with math problems)","2-6","","$3","Web","LootEarly","https://dig-itgames.com/portfolio/maya-math-education-game/",,,true],
["WorkBook","No","Loot Pursuit: Maya","Math","Math practice (visual novel intercut with math problems)","2-6","","$3","Web","LootMaya","https://dig-itgames.com/portfolio/maya-math-education-game/",,,true]];