var list = [
["Edu","Programming","No","Basic Programming (Drag 'n drop)","Turtle Academy","4+","<1","0","Flash","TurtleAcademy","https://www.brainpop.com/games/turtleacademy/",,,],
["Edu","Programming","No","Basic Programming (Drag 'n drop)","Run Marco!","4+","1","0","Web","RunMarko","https://www.brainpop.com/games/runmarco/",,,],
["Edu","Programming","No","Basic Programming (Drag 'n drop)","Blockly: Maze","3+","<1","0","Web","BlocklyMaze","https://www.brainpop.com/games/blocklymaze/",,,],
["Edu","Programming","Yes","Basic Programming (Typing)","Codecombat: Ogre Encounter","5+","Class","0","Web","CodeCombat","https://www.brainpop.com/games/codecombatogreencounter/",,,],
["Edu","Math","Maybe","Vaguely teaches fraction estimation","Slice Fractions: School Edition","3-5","<1","0/$5","Flash","SliceFractions","https://www.brainpop.com/games/slicefractionsschooledition/",,,],
["Edu","Math","Yes","Geometry (Contains serious math)","A Tangled Web","7+","2","0","Web","TangledWeb","https://www.brainpop.com/games/atangledweb/",,,],
["Edu","Math","Yes","Geometry (unreasonably difficult)","Pyramid Panic","3+","<1","0","Flash","PyramidPanic","https://www.brainpop.com/games/pyramidpanic/",,,],
["Edu","Math","Maybe","Perimeter","Square Off","3+","<0.25","0","Flash","SquareOff","https://www.brainpop.com/games/squareoff/",,,],
["Edu","Math","Maybe","Perimeter and Area","Area Builder","3+","<0.25","0","Web","AreaBuilder","https://www.brainpop.com/games/areabuilder/",,,],
["Edu","Physics","Yes","Levers/Balances","Balancing Act","4+","<0.5","0","Web","BalancingAct","https://www.brainpop.com/games/balancingact/",,,],
["Edu","Physics","Maybe","Levers, pulleys, wheels, inclined planes","Simple Machines Game","3-8","<0.25","0","Flash","SimpleMachines","https://www.brainpop.com/games/simplemachinesgame/",,,],
["Edu","Astro-Physics","Yes","Astronomy: Phases of Sun, Moon, and constellations","Chronopticon","5+","<1","0","Flash","Chronopticon","https://www.brainpop.com/games/chronopticon/",,,],
["Edu","Astro-Physics","YES!","Orbital mechanics (EDU version also available)","Kerbal Space Program","9+","∞","40","exe","KSP","http://store.steampowered.com/app/220200/Kerbal_Space_Program/",,,],
["Edu","Government","Yes","Getting a bill through the legislative branch","Lawcraft","6+","<1","0","Flash","LawCraft","https://www.brainpop.com/games/lawcraft/",,,],
["Edu","Misc.","YES!","Food prep safety","Ninja Kitchen","5+","<1","0","Flash","NinjaKitchen","https://www.brainpop.com/games/ninjakitchen/",,,],
["Edu","Physics","Yes","Constructive and destructive wave interference","Wave Combinator","6+","<0.5","0","Web","WaveCombinator","https://www.brainpop.com/games/wavecombinator/",,,],
["Edu","Physics","Yes","High and low pressure weather systems","Wind Simulator","4+","<0.5","0","Web","","https://www.brainpop.com/games/windsimulator/",,,],
["Edu","Weather","Yes","Atomspheric measurements to predict disasters","Disaster Detector","5+","1","0","Flash","DisasterDetector","https://ssec.si.edu/disaster-detector",,,],
["Edu","Physics","Yes","Buoyancy","Hot Air Balloon","3+","<0.5","0","Web","HotAirBalloon","https://www.brainpop.com/games/hotairballoon/",,,],
["Edu","Physics","Yes","Magnets and electromagnets","Magnethunt","3+","<0.75","0","Web","MagnetHunt","https://www.brainpop.com/games/magnethunt/",,,],
["Edu","Physics","Yes","Magnets and magnetic fields","The Electric Shocktopus","6+","<0.5","0/$6","exe","Shocktopus","http://testtubegames.com/shocktopus.html",,,],
["Edu","Physics","Yes","Relativity and near light speed travel","Velocity Raptor","9+","1","0","Web","VelocityRaptor","http://testtubegames.com/velocityraptor.html",,,],
["Edu","Physics","Yes","Heliocentric/Geocentric models and related physics","Odyssey: The Invention of Science","4-10","5","15","exe","Odyssey","http://store.steampowered.com/app/558110/Odyssey__The_Next_Generation_Science_Game/",,,],
["Edu","Physics","Yes","Subatomic particle mechanics","Particulars","9+","7","6","exe","Particulars","http://store.steampowered.com/app/259470/Particulars/",,,],
["Edu","Physics","Yes","Quantum mechanics","Quantum Marble Maze","9+","1","0",".jar","QuantumMarbleMaze","http://tropic.org.uk/~crispin/quantum/",,,],
["Edu","Physics","Yes","Atoms bonding","Bond Breaker","7+","2","0","Unity Web GL","BondBreaker","http://testtubegames.com/bondbreaker.html",,,],
["Edu","Misc.","","Very basic music mixing","One Man Band","0-4","<0.25","0","Flash","OneManBand","https://www.brainpop.com/games/onemanband/",,,],
["Edu","Geography","Maybe","Cities, their location, and a very brief history","Carmen Sandiago","varies","varies","0","DOS","CarmenSandiago","https://classicreload.com/where-in-the-world-is-carmen-sandiego-deluxe-edition.html ",,,],
["Edu","Government","Yes","Bill of rights (best of this series)","Do I Have A Right?","","","0","Web","","https://www.brainpop.com/games/doihavearight/",,,],
["Edu","Government","Maybe","Government: Court system of the US","Court Quest","6+","0.25","0","Flash","CourtQuest","https://www.brainpop.com/games/courtquest/",,,],
["Edu","Government","No","Ideals of the Democratic and Repubilcan parties","Win The White House","9+","<0.5","0","Web","WinWhiteHouse","https://www.brainpop.com/games/winthewhitehouse/",,,],
["Edu","Government","Maybe","Pass a law through 3 branches of US federal government","Branches Of Power","4+","<0.5","0","Flash","BranchesOfPower","https://www.brainpop.com/games/branchesofpower/",,,],
["Edu","Government","NO!","Political personality test","Cast Your Vote","0","<0.25","0","Flash","CastYourVote","https://www.brainpop.com/games/castyourvote/",,,],
["Edu","Government","Maybe","Perform the duties of the president","Executive Command","3+","<0.5","0","Web","ExecutiveCommand","https://www.brainpop.com/games/executivecommand/",,,],
["Edu","Government","Yes","Rules for immigrating to the US","Immigration Nation","3+","<0.5","0","Flash","ImmigrationNation","https://www.icivics.org/games/immigration-nation",,,],
["Edu","Government","No","Act as a juror on a court case","We The Jury","","","0","Flash","","https://www.brainpop.com/games/wethejury/",,,],
["Edu","History","Maybe","Historic Supreme Court cases","Argument Wars","","","0","Flash","","https://www.brainpop.com/games/argumentwars/",,,],
["Edu","Government","No","Manage a social advocacy group","Activate","","","0","Flash","","https://www.brainpop.com/games/activate/",,,],
["Edu","Government","Maybe","Bureaucracy","Counties Work","","","0","Web","","https://www.brainpop.com/games/countieswork/",,,],
["Edu","Government","Yes","Federal Budget","People's Pie","","","0","Flash","PeoplesPie","https://www.brainpop.com/games/peoplespie/",,,],
["Edu","None!","Maybe","Stereotyping ","Represent Me","","","0","Flash","","https://www.brainpop.com/games/representme/",,,],
["HW","Math","NO!","Random school adjacent quizes.","Dino School Series","2+","2","0","Android","","https://play.google.com/store/apps/details?id=co.familyplay.dinograde5free",,,],
["HW","Many","NO!","Random games with quiz questions jamed in ","_ Grade Learning Games Series","4+","2","0/$4","Android","SixthGradeLearningGames","https://play.google.com/store/apps/details?id=com.kevinbradford.games.sixthgrade",,,],
["Edu","Math","YES!","Graphing equations and equations graphs","Sine Rider","6+","3","0","exe","","http://sineridergame.com/",,,],
["Edu","Math","No","Just play Sine Rider","Quations","","<1/4","0","","","https://www.newgrounds.com/portal/view/680544",,,],
["Edu","Government","No","How the Supreme court makes decisions","Supreme Decision","","","0","Flash","","https://www.brainpop.com/games/supremedecision/",,,],
["Sim","Government","No","Infrastructure management","Ostevera","3+","<0.5","0","Web","Ostevera","https://ostevera.spongelab.com/game/index.cfm",,,],
["Issue","Issue","No","The effects of war on civilians","This War Of Mine","","","20","exe","","http://store.steampowered.com/app/282070/This_War_of_Mine/",,,],
["Issue","Issue","Maybe","Invasive species","Invasion!!","","","0","Flash","","https://www.brainpop.com/games/invasion/",,,],
["Issue","Issue","No","Gay relationships","Sam And Nicole","","","0","exe","","https://sigridsanglar.itch.io/sam-and-nicole-demo",,,],
["Issue","Issue","No","Getting water in Africa","Yaku International","0+","<0.5","0","Web","YakuInternational","http://www.kongregate.com/games/MouseCity/yaku-international",,,],
["Issue","Issue","Maybe","Waste managment and pollution","Super Energy Apocalypse","","1","0","","SuperEnergyApocalypse","http://www.newgrounds.com/portal/view/430963",,,],
["Issue","Issue","No","Vague idea of the world's drinkable water supply system.","Aquation","0+","<0.25","0","Web","Aquation","http://ssec.si.edu/sites/default/files/games/Aquation/index.html",,,],
["Issue","Issue","No","Pollution","SimCity Edu: Pollution Challenge","3+","","","exe","","https://www.glasslabgames.org/games/SC",,,],
["Edu","Physics","Yes","Heat transfer","Galactic Gloop Zoo","","","0","Flash","","http://cct2.edc.org/rubyrealm/module4/bin/Module4.html",,,],
["Edu","Biology","Yes","Cellular processes","The Ruby Realm","","","0","Flash","","http://cct2.edc.org/rubyrealm/bin/RubyRealmFlash.html",,,],
["Edu","Biology","Maybe","Punnett squares","Roboriot","","","0","Flash","","http://cct2.edc.org/rubyrealm/roboriot2/bin/RoboRiot.html",,,],
["Edu","Biology","Yes","Punnett squares","Fuzzies","","","0","","","https://www.newgrounds.com/portal/view/544333",,,],
["Edu","Biology","Maybe","Components of immune cells.","Immune Defense","6+","2","0","Flash","ImmuneDefense","https://www.kongregate.com/games/DrAnn/immune-defense",,,],
["Edu","Biology","Maybe","Cell wall basics","Cell Defense","6+","<0.5","0","Web","CellDefense","https://biomanbio.com/HTML5GamesandLabs/Cellgames/celldefensehtml5page.html",,,],
["Edu","Biology","","","Osy Osmosis","","","$3","exe","","http://www.osyosmosis.com/",,,],
["Edu","","","","Phylo: The DNA Puzzle Game","","","0","Web","","https://phylo.cs.mcgill.ca/#",,,],
["Edu","None!","No","Not a lot honestly (it's supposed to teach about electricity)","Monster Music","2+","","0","Flash","","http://cct2.edc.org/rubyrealm/monstermusic2/bin/MonsterMusic.html",,,],
["Edu","Biology","Yes","Human systems","Code Fred: Survival Mode","4+","<0.5","0","Flash","CodeFred","https://www.brainpop.com/games/codefredsurvivalmode/",,,],
["Edu","Biology","Yes","Components in a cell","Cellcraft","","","0","Flash","","https://www.kongregate.com/games/cellcraft/cellcraft",,,],
["Edu","Biology","Yes","Ligands","Ligand Quest","","","0","exe","","https://artii.itch.io/ligandquest",,,],
["Edu","Biology","Yes","Microscopic tour of ?human? cells and systems","Metablast","","","0","exe","","http://www.metablast.org/",,,],
["Edu","Biology","No","Sepsis (a disease)","Sepsis","","<1/2","0","Flash","","http://www.newgrounds.com/portal/view/382253",,,],
["Edu","Biology","Maybe","Evolutionary Trees: very tutorial heavy","Life Preservers","1+","<1/4","0","Unity Web","","https://www.brainpop.com/games/lifepreservers/",,,],
["Edu","","","","Morphy!","","","0","ipad Only?","Morphy","https://ssec.si.edu/morphy",,,],
["Edu","Biology","","Don't know. IOS store won't admit it even exists.","Bacteria Combat","8+","0","0/?","ipad Only?","BacteriaCombat","http://gamedrlimited.com/bacteria-combat",,,],
["Edu","Biology","","Don't know. IOS store won't admit it even exists.","SYNMOD Game ","","","0","IOS","","https://www.biofaction.com/portfolio/synmod-game/",,,],
["Edu","Biology","","Genes and genotypes","Dragon Breeder","8+","","0","Web","DragonBreeder","http://www.spongelab.com/interactives/dragon_breeder/index.cfm",,,],
["Edu","Language","Yes","German Language","Lost In Dutchland","0+","","0","exe or Web GL","","https://gamejolt.com/games/Lost_In_Deutschland/289399",,,],
["Edu","Biology","No","Evolution","Flap To The Future","2+","<1/4","0","Web","","https://www.brainpop.com/games/flaptothefuture/",,,],
["Edu","Biology","No","Human immune cells","Immune Quest","13+","2","0/$15","exe","","http://immunequest.com/",,,],
["Edu","History","Yes","Native Americans","Mission Us: A Cheyenne Odyssey","5+","","0","Flash","","https://www.brainpop.com/games/missionusacheyenneodyssey/",,,],
["Edu","History","Yes","1820s life in NY as an immigrant","Mission Us: City Of Immigrants","5+","","0","Flash","","https://www.brainpop.com/games/missionuscityofimmigrants/",,,],
["Edu","History","Yes","The American Dust Bowl","Mission Us: Up From The Dust","5+","","0","Flash","","https://www.brainpop.com/games/missionusupfromthedust/",,,],
["Edu","Literature","Maybe","Philosophy: Henry David Thoreau doing very little","Walden","7+","","0","","","https://gameinnovationlab.itch.io/walden",,,],
["Edu","Biology","Yes","Food chain","Food Chain Game","","<1/4","0","Flash","","https://www.brainpop.com/games/foodchaingame/",,,],
["Edu","Biology","No","Food chain: couldn't figure out how to play","Food Fight","","<1/4","0","Web","Exotrex","https://www.brainpop.com/games/foodfight/",,,],
["Edu","","No","element symbols","Exotrex"," and identifying renewable and nonrenewable resources"," subatomic particles","$6","Web","","https://dig-itgames.com/portfolio/exotrex-game-science-space-grade8/",,,],
["Edu","","No","relative distances between planets and other celestial bodies","Exotrex2",""," as well as Newton's third law","$6","Web","6-10","https://dig-itgames.com/portfolio/exotrex2-science-planetary_game/",,,],
["Edu","Math","Yes","Logic puzzles and proofs (propositional calculus)[Profanity]","Rational Redux","6+","<1","0","Flash(works in chrome)","RationalRedux","http://www.kongregate.com/games/tjubert/ir-rational-redux",,,],
["Tool","Anything","Yes","It takes a skilled teacher to make this worth using.","Minecraftedu","0+","∞","???","exe","MinecraftEdu","https://education.minecraft.net/",,,],
["Tool","Graphing","","","","","∞","0","Web","","https://www.geogebra.org/",,,],
["Tool","Graphing","","","Desmos","","∞","0","Web","","https://www.desmos.com/",,,],
["WorkBook","History","No","An archiologist looks at Byzantine culture","Excavate! Byzantine Education Game","","","$4","multiple","ExcavateByzantine","https://dig-itgames.com/portfolio/excavate-byzantine-social-studies-game/",,,],
["WorkBook","History","No","An archiologist looks at Mesopotamian culture","Excavate! Mesopotamia","","","$4","multiple","ExcavateMesopotamia","https://dig-itgames.com/portfolio/excavate-mesopotamia-world-history-game-culture/#Mat",,,],
["WorkBook","History","No","An archiologist looks at Egyptian culture","Excavate! Egypt","","","$4","multiple","ExcavateEgypt","https://dig-itgames.com/portfolio/excavate-egypt-world-history-lesson-game/",,,],
["WorkBook","History","No","An archiologist looks at Mesoamerican culture","Excavate! Mesoamerica","","","$4","multiple","ExcavateMesoamerica","https://dig-itgames.com/portfolio/excavate-mesoamerica-inca-maya-history-game/",,,],
["WorkBook","History","No","An archiologist looks at anchient Greek culture","Excavate! Greece","","","$4","multiple","ExcavateGreece","https://dig-itgames.com/portfolio/excavate-greece-world-history-greek/",,,],
["WorkBook","History","No","An archiologist looks at anchient Roman culture","Excavate! Rome","","","$4","multiple","ExcavateRome","https://dig-itgames.com/portfolio/excavate-ancient-rome-social-studies/",,,],
["Edu","History","NO!","Random mini-games intercut with Roman culture","Roman Town 2","","","$1","multiple","RomanTown2","https://dig-itgames.com/portfolio/roman-town-2-social-studies-puzzles/",,,],
["WorkBook","Math","No","Math practice (visual novel intercut with math problems)","Loot Pursuit: Early America","2-6","","$3","Web","LootEarly","https://dig-itgames.com/portfolio/maya-math-education-game/",,,],
["WorkBook","Math","No","Math practice (visual novel intercut with math problems)","Loot Pursuit: Maya","2-6","","$3","Web","LootMaya","https://dig-itgames.com/portfolio/maya-math-education-game/",,,],
["Edu","Many","No","What 2010 thought textbooks would be in 2020.","Brilliant.org","9+","∞","0/25month","Web","Brillian","Brilliant.org",,,],
["Edu","Many","","What 2020 textbooks should look like.","CK-12","","","0","Web","","https://www.ck12.org/student/",,,],
["Edu","Job","No","Working at a news company","The Sports Network 2","4+","","0","Flash","","https://www.brainpop.com/games/thesportsnetwork2/",,,],
["Issue","Issue","NO!","morality (very vague and unhelpful) (propaganda)","Digital Compass","2-4","","0","Flash","","https://www.brainpop.com/games/digitalcompass/",,,],
["Edu","Job","Yes","Job as a pathologist","Medmyst Animal Alert!","6+","","0","Flash","","https://www.brainpop.com/games/medmystanimalalert/",,,],
["Edu","Managment","Yes","Making decisions based on public opinion","Quandary","4+","","0","Web","","https://www.brainpop.com/games/quandary/",,,],
["Edu","Job","Yes","Job at a modern newspaper","After The Storm: Day One","6+","","0","Web","","https://www.brainpop.com/games/afterthestormdayone/",,,],
["Edu","Job","No","Running a community center","Community In Crisis: Aftermath","6+","","0","Web","","https://www.brainpop.com/games/communityincrisistheaftermath/",,,],
["HW","Math","Yes","Math practice (addition) [Actually good]","Addition Blocks","1-4","","0","Web","","https://www.brainpop.com/games/additionblocks/",,,],
["HW","Math","Yes","Math practice (multiplication) [Actually good]","Multiplication Blocks","2-4","","0","Web","","https://www.brainpop.com/games/multiplicationblocks/",,,],
["HW","Math","Yes","Math practice (MATH PUNCHER!)","La Torre De Nozar","2-4","","0","exe","","https://sebagames.itch.io/la-torre-de-nozar",,,],
["HW","Math","YES!","Math practice (addution and subtraction)","Gate","2-4","","0","Flash","","https://www.brainpop.com/games/gate/",,,],
["HW","Math","Maybe","Math practice (+ - x / primes)","Number Munchers","1-4","","0","","","https://classicreload.com/number-munchers.html",,,],
["HW","Math","No","Math practice (confusing)","Lure Of The Labyrinth: Cafeteria","","","0","Flash","","https://www.brainpop.com/games/lureofthelabyrinthemployeecafeteria/",,,],
["HW","Math","No","Math practice (confusing)","Math Blaster (Original)","1-4","","0","","","https://classicreload.com/math-blaster-plus.html",,,],
["HW","Math","No","Math practice and educational mini-games","Math Blaster (Modern)","0-4","","0","exe","","http://www.mathblaster.com/",,,],
["HW","Math","No","Math practice (confusing)","Lure Of The Labyrinth: Lounge","","","0","Flash","","https://www.brainpop.com/games/lureofthelabyrinthemployeelounge/",,,],
["HW","Math","No","Math practice (confusing)","Lure Of The Labyrinth: Mine","","","0","Flash","","https://www.brainpop.com/games/lureofthelabyrinthmineshaft/",,,],
["HW","Math","No","Math practice (very boring)","Number Jumble","1-4","","0","Flash","","https://www.brainpop.com/games/numberjumble/",,,],
["HW","Math","Maybe","Math practice (relatively complicated)","Primary Krypto","1-4","","0","Flash","","https://www.brainpop.com/games/primarykrypto/",,,],
["HW","Math","No","Math practice (Visual multiplication)","Teachley Mt. Multiplis","","","0","Web","","https://www.brainpop.com/games/teachleymtmultiplis/",,,],
["HW","Math","No","Math practice (addition)","Deep Sea Duel","1-4","","0","Flash","","https://www.brainpop.com/games/deepseaduel/",,,],
["HW","Math","Yes","Math practice (addition)","Addition Snowball Fight","1-4","","0","","","https://www.newgrounds.com/portal/view/489100",,,],
["HW","Math","No","Math practice (addition and subtraction)","Jelly Bean","1-2","","0","Flash","","https://www.brainpop.com/games/jellybean/",,,],
["HW","Math","No","Math practice / word problems (bad user interface)","Riddlebooks","2-4","","0","Flash","","https://www.brainpop.com/games/riddlebooks/",,,],
["HW","Math","No","Math practice (RPG with math poorly replacing combat)","Mathoria (Series)","","","0","exe","","http://store.steampowered.com/app/434480/Mathoria_It_All_Adds_Up/",,,],
["HW","Math","No","Math practice (visual novel intercut with math problems)","Loot Pursuit: Pompeii","2-6","","0/$4","IOS","LootPompeii","https://itunes.apple.com/us/app/loot-pursuit-pompeii/id853849610?mt=8",,,],
["HW","Biology","YES!","GI-Tract (learn parts of the digestion system)","Gi-Tract Chain Game","4+","","0","","","https://www.newgrounds.com/portal/view/650397",,,],
["HW","Biology","Maybe","Human Amino Acids (test with no tutorial at all)","Amino Acid Match Game","","","0","","","https://www.newgrounds.com/portal/view/631652",,,],
["HW","Biology","Maybe","Glycolysis (trial and error matching game)","Glycolysis Match Game","","","0","","","https://www.athleticarcade.com/educational/match/glycolysis.html",,,],
["HW","Biology","No","Something about ecosystems???","Ibiome-Wetland School Edition","","","0","Flash","","https://www.brainpop.com/games/ibiomewetlandschooledition/",,,],
["HW","Biology","Maybe","A citizen science game about identifing bugs","Forgotten Island","4+",">2","0","Flash","Forgotten Island","https://citizensort.org/web.php/forgottenisland",,,],
["HW","Biology","NO!","Biology test with a game theme.","Knowledge Mine","12+","2","0","Flash","KnowledgeMine","http://www.spongelab.com/interactives/km/",,,],
["HW","Literature","No","Greek Alphabet: trial and error matching game","Greek Alphabet Match Game","","","0","","","https://www.athleticarcade.com/educational/match/greek-alphabet.html",,,],
["HW","Math","No","Homweork for various types of math problems","Adapted Mind - Math","1-6","","$10/m","Web","AdaptedMath","http://www.adaptedmind.com/Math-Worksheets.php",,,],
["HW","Literature","NO!","Literature test prep","Adapted Mind - Reading","1-6","","0/$10/m","Web","AdaptedReading","http://www.adaptedmind.com/reading.php",,,],
["HW","Physics","No","What color metals burn","Production Line","6+","<1/4","0","Web","ProductionLine","http://www.kongregate.com/games/ChrisM15/production-line",,,],
["HW","Physics","Yes","Waveform/Sound association","Bird Song Hero","4+","","0","Web","","https://www.brainpop.com/games/birdsonghero/",,,],
["HW","Literature","No","French","Lost In Translation","0+","","0","exe  Unreal 4","","https://mottomi.itch.io/lost-in-translation",,,],
["HW","Physics","Yes","Sort Solids, liquids, gases, and plasmas","Matter Sorter","","<1/4","0","Flash","","https://www.brainpop.com/games/mattersorter/",,,],
["HW","Math","No","Add and subtract by fixed values (difficult controls)","Wuzzit Trouble","1-4","","0","Firefox","","https://www.brainpop.com/games/wuzzittrouble/",,,],
["HW","Math","Yes","Fractions/Decimals practice (0 to 1)","Treefrog Treasure","1-4","","0","Flash","","https://www.brainpop.com/games/treefrogtreasure/",,,],
["HW","Math","Yes","Fractions/Decimals estimation practice","Battleship Numberline","1-4","","0","Flash","","https://www.brainpop.com/games/battleshipnumberline/",,,],
["HW","Math","No","Fractions practice (0 to 9)","Dig It","1-4","","0","Flash","","https://www.brainpop.com/games/digit/",,,],
["HW","Math","No","Fractions practice (adding to 1)","Drop Zone","1-4","","0","Flash","","https://www.brainpop.com/games/dropzone/",,,],
["HW","Math","No","Couldn't figure this one out","Flower Power","","","0","Web","","https://www.brainpop.com/games/flowerpower/",,,],
["HW","Math","No","Adding to 10","Monster School Bus","1-2","","0","Flash","","https://www.brainpop.com/games/monsterschoolbus/",,,],
["HW","Math","No","Number estimation and button mashing","Pearl Diver","","","0","Flash","","https://www.brainpop.com/games/pearldiver/",,,],
["HW","Math","No","Ratio practice","Ratio Rumble","1-4","","0","Flash","","https://www.brainpop.com/games/ratiorumble/",,,],
["HW","Government","No","3 US Federal Gov. Branches Test","Branches Of Government Game","","","0","Flash","","https://www.brainpop.com/games/branchesofgovernmentgame/",,,],
["HW","Government","No","3 US Federal Gov. Branches Test","Checks And Balances","","","0","Flash","","https://www.brainpop.com/games/checksandbalances/",,,],
["HW","Health","No","Create a day's worth of balanced meals","Chef Solus' Build-A-Meal","","","0","Flash","","https://www.brainpop.com/games/chefsolusbuildameal/",,,],
["HW","Literature","No","You are an editor (very bland)","Quill","","","0","Flash","","https://www.brainpop.com/games/quill/",,,],
["HW","Biology","Maybe","How cancer is detected and treated","Oncology","","","0","Flash","","https://www.brainpop.com/games/oncology/",,,],
["HW","Physics","Maybe","Folding proteins","Foldit","9+","∞","0","exe","","https://fold.it/",,,],
["HW","Geography","Yes","Test names, capitals, or flags of world countries.","World Countries Quiz","","","0","","","https://www.newgrounds.com/portal/view/629856",,,],
["HW","Geography","No","Test names or cities of European countries","Conquering Europe","","","0","","","https://www.newgrounds.com/portal/view/625046",,,],
["HW","Literature","No","Test for the book Lord of the Flies","Lord Of The Flies","","","0","Flash","","https://www.brainpop.com/games/lordoftheflies/",,,],
["HW","Physics","No","Text dumps","Theoreum","","<1/4","0","exe","","https://misfitvillage.itch.io/theoreum",,,],
["HW","Biology","Yes","Human systems inputs and outputs","Guts And Bolts","","","0","Web","","https://www.brainpop.com/games/gutsandbolts/",,,],
["HW","Biology","Yes","Human Biology: drag 'n drop","Build-A-Body: Digestive System","","","0","Flash","","https://www.brainpop.com/games/buildabodydigestivesystem/",,,],
["HW","Biology","Maybe","Human Biology: drag 'n drop","Organ Transplant 2","","","0","","","https://www.newgrounds.com/portal/view/600659",,,],
["HW","Biology","No","Human Biology: Fill in the blank","Immune System Game","","","0","","","https://www.newgrounds.com/portal/view/478787",,,],
["HW","Biology","Yes","Tree Biology: drag 'n drop","Build-A-Tree","","","0","Flash","","https://www.brainpop.com/games/buildatree/",,,],
["HW","Literature","No","Vocabulary (sorting by association)","Sortify (Series)","","","0","Web","","https://www.brainpop.com/games/sortify/",,,],
["HW","Programming","Maybe","Basic programming (Drag 'n drop)","Tynker (Series)","","","0","Flash","","https://www.brainpop.com/games/game-finder/?game_keyword=developer:%20Tynker",,,],
["HW","History","No","Historical timelines","Time Zone X (Series)","","","0","Web","","https://www.brainpop.com/games/timezonex/",,,],
["HW","Literature","No","Vocabulary","The Meaning Of Beep (Series)","","","0","Web","","https://www.brainpop.com/games/themeaningofbeep/",,,],
["HW","Chemistry","No","Build Molecules","Chemistry","","<3/4","0","","","https://www.newgrounds.com/portal/view/635310",,,],
["HW","Physics","Maybe","Gravity","Circle Master 2","4+","<0.5","0","Web","CircleMaster","http://www.kongregate.com/games/akane2002/circle-master-2-gravitation",,,],
["HW","Biology","No","A walking simulator / quiz game about plants.","Solarium","6+","1","0","exe","Solarium","http://sunfleck.com/",,,],
["Sim","Astro-Physics","No","2D orbital mechanics sim","Build A Solar System","","<1/4","0","Flash","","https://www.brainpop.com/games/buildasolarsystem/",,,],
["Sim","Physics","Yes","Light spectrum and vision","Color Vision","","<1/4","0","Web","","https://www.brainpop.com/games/colorvision/",,,],
["Sim","Physics","Yes","Light interaction with particles","Molecules And Light","","<1/4","0","Web","","https://www.brainpop.com/games/moleculesandlight/",,,],
["Sim","Physics","Yes","Many physics simulations","Phet Interactive Simulations","0+","a lot","0","Web","Phet","https://phet.colorado.edu/",,,],
["Sim","Many","","Many physics simulations","Explore Learning","3+","a lot","","","","https://www.explorelearning.com/",,,],
["Sim","","","","SimCityEDU","","","","","","https://www.glasslabgames.org/games/SC",,,],
["Sim","Government","No","Balancing the US federal budget","The Fiscal Ship","","<1/4","0","Web","","https://www.brainpop.com/games/thefiscalship/",,,],
["Sim","Biology","Yes","Biological inputs of plants: Water, light, CO2","What Plants Need","","<1/4","0","Flash","","https://www.brainpop.com/games/whatplantsneed/",,,],
["Sim","Physics","No","Desalinating water (I couldn't figure it out)","Desalination","","<1/4","0","Flash","","https://www.brainpop.com/games/desalination/",,,],
["Sim","Biology","Maybe","Neuropsychology, toxicology, epidemiology, neurobiology","Cool Science Careers: Imagine Y.","","","0","Flash","","https://www.brainpop.com/games/coolsciencecareersimagineyourself/",,,],
["Sim","Government","Yes","Gerrymandering ","District","","","0","Web","","http://polytrope.com/district/",,,],
["Sim","Math","Yes","Statistics of population diversity","Parable Of The Polygons","","<1/2","0","Web","","http://ncase.me/polygons/",,,],
["Sim","History","No","American revolution timeline","American Revolution Timeline","","<1/4","0","Flash","","https://www.brainpop.com/games/americanrevolutiontimeline/",,,],
["Sim","Misc.","No","Phycology: Pavlov's dog and that's it","Pavlov's Dog","","<1/4","0","Flash","","https://www.brainpop.com/games/pavlovsdog/",,,],
["Sim","Chemistry","No","Solution concentrations","Concentration","","<1/4","0","Web","","https://www.brainpop.com/games/concentration/",,,],
["Sim","Physics","Yes","Energy = Potential + Kinetic + Friction losses","Energy Skate Park: Basics","","<1/4","0","Web","","https://www.brainpop.com/games/energyskateparkbasics/",,,],
["Sim","Math","No","Graphs","Graphing Lines","","<1/4","0","Web","","https://www.brainpop.com/games/graphinglines/",,,],
["Sim","Physics","Maybe","Waves","Wave On A String","","<1/4","0","Web","","https://www.brainpop.com/games/waveonastring/",,,],
["Sim","Physics","Maybe","Quantum mechanics (uncertainty)","Quantum Minigolf","","<1/4","0","exe","","http://quantumminigolf.sourceforge.net/",,,],
["Sim","Astro-Physics","No","Shows scale of planetary/universal bodies","Sizing Up The Universe","","<1/4","0","Web","","https://www.brainpop.com/games/sizinguptheuniverse/",,,],
["Sim","Physics","","Gravity","Gravity Simulator","6+","∞","0/$6","Web","GravitySimulator","http://testtubegames.com/gravity.html",,,],
["Sim","Astro-Physics","Maybe","Orbits and other planetary physics","Universe Sandbox","","<1/4","25","exe","","http://store.steampowered.com/app/230290/Universe_Sandbox/",,,],
["Sim","Physics","No","Not a lot (Was obviously made for a museum)","Csi: Flight Adv. Forces Of Flight","","<1/4","0","Flash","","https://www.brainpop.com/games/csiflightadventuresforcesofflight/",,,],
["Sim","Physics","No","Not a lot (Was obviously made for a museum)","Csi: Flight Adv. Flight School","","<1/4","0","Flash","","https://www.brainpop.com/games/csiflightadventuresflightschool/",,,],
["Sim","History","No","Dinosaurs (Was obviously made for a museum)","Construct-A-Saurus","","<1/4","0","Flash","","https://www.brainpop.com/games/constructasaurus/",,,],
["Sim","Misc.","No","Stock market game (exactly as boring as it sounds)","Stock Market Game","","<1/4","0","","","https://www.newgrounds.com/portal/view/410269",,,],
["Sim","Biology","No","Basic fish anatomy and artificial selection","Sticky Outie Bits","","<1/4","0","","","https://www.newgrounds.com/portal/view/629919",,,],
["Vid","Job","No","Water concentration in food affects shelf life","Virtual Labs: U. Water Activity","","<1/2","0","Flash","","https://www.brainpop.com/games/virtuallabsunderstandingwateractivity/",,,],
["Vid","Job","No","Brief overview of some jobs","Virtual Labs (Series)","","<1/2","0","Flash","","https://www.brainpop.com/games/game-finder/?game_keyword=developer:%20NMSU%20Learning%20Games%20Lab",,,],
["Vid","Misc.","No","Watch www.youtube.com/watch?v=8YmiRfCDeNg instead","Drake Equation","","<1/4","0","Flash","","https://www.brainpop.com/games/drakeequation/",,,],
["Vid","Biology","No","Ecosystems of microbes","Close-Knit Neighbors","","<1/4","0","Flash","","https://www.brainpop.com/games/closeknitneighbors/",,,],
["Vid","History","","Moon Landing","Apollo 11 VR","","","0","VR Game","","http://store.steampowered.com/app/457860/Apollo_11_VR/",,,],
["Vid","History","","Titanic","Titanic VR","","","0","VR Game","","http://store.steampowered.com/app/741430/Titanic_VR/",,,],
["Vid","Biology","NO!","Ebola Virus (slide show with terrible game at the end)","Operation Ebola!","9+","<0.25","0","Web","Ebola","https://catlilli.itch.io/ebola",,,],
["Vid","Astro-Physics","NO!","Flight simulator for historical space flights.","Space Simulator","4+","2?","10","exe","SpaceSimulator","https://store.steampowered.com/app/529060/Space_Simulator/",,,],
["Vid","Biology","No","Zoom in on cells to see them at different magnifications","Powers of Minus Ten","6+","<1","$2","IOS","POMT","http://powersofminusten.com/",,,]];