var list = [["Edu","No","Turtle Academy","Programming","Basic Programming (Drag 'n drop)","4+","1-","0","Flash","TurtleAcademy","https://www.brainpop.com/games/turtleacademy/",,,true],
["Edu","No","Run Marco!","Programming","Basic Programming (Drag 'n drop)","4+","1","0","Web","RunMarko","https://www.brainpop.com/games/runmarco/",,,true],
["Edu","No","Blockly: Maze","Programming","Basic Programming (Drag 'n drop)","3+","1-","0","Web","BlocklyMaze","https://www.brainpop.com/games/blocklymaze/",,,true],
["Edu","Yes","Codecombat: Ogre Encounter","Programming","Basic Programming (Typing)","5+","Class","0","Web","CodeCombat","https://www.brainpop.com/games/codecombatogreencounter/",,,true],
["Edu","Maybe","Slice Fractions: School Edition","Math","Vaguely teaches fraction estimation","3-5","1-","0/$5","Flash","SliceFractions","https://www.brainpop.com/games/slicefractionsschooledition/",,,true],
["Edu","Yes","A Tangled Web","Math","Geometry (Contains serious math)","7+","2","0","Web","TangledWeb","https://www.brainpop.com/games/atangledweb/",,,true],
["Edu","Yes","Pyramid Panic","Math","Geometry (unreasonably difficult)","3+","1-","0","Flash","PyramidPanic","https://www.brainpop.com/games/pyramidpanic/",,,true],
["Edu","Maybe","Square Off","Math","Perimeter","3+","0.25-","0","Flash","SquareOff","https://www.brainpop.com/games/squareoff/",,,true],
["Edu","Maybe","Area Builder","Math","Perimeter and Area","3+","0.25-","0","Web","AreaBuilder","https://www.brainpop.com/games/areabuilder/",,,true],
["Edu","Yes","Balancing Act","Physics","Levers/Balances","4+","0.5-","0","Web","BalancingAct","https://www.brainpop.com/games/balancingact/",,,true],
["Edu","Maybe","Simple Machines Game","Physics","Levers, pulleys, wheels, inclined planes","3-8","0.25-","0","Flash","SimpleMachines","https://www.brainpop.com/games/simplemachinesgame/",,,true],
["Edu","Yes","Chronopticon","Astro-Physics","Astronomy: Phases of Sun, Moon, and constellations","5+","1-","0","Flash","Chronopticon","https://www.brainpop.com/games/chronopticon/",,,true],
["Edu","YES!","Kerbal Space Program","Astro-Physics","Orbital mechanics (EDU version also available)","9+","∞","$40","exe","KSP","http://store.steampowered.com/app/220200/Kerbal_Space_Program/",,,true],
["Edu","Yes","Lawcraft","Government","Getting a bill through the legislative branch","6+","1-","0","Flash","LawCraft","https://www.brainpop.com/games/lawcraft/",,,true],
["Edu","YES!","Ninja Kitchen","Misc.","Food prep safety","5+","1-","0","Flash","NinjaKitchen","https://www.brainpop.com/games/ninjakitchen/",,,true],
["Edu","Yes","Wave Combinator","Physics","Constructive and destructive wave interference","6+","0.5-","0","Web","WaveCombinator","https://www.brainpop.com/games/wavecombinator/",,,true],
["Edu","Yes","Wind Simulator","Physics","High and low pressure weather systems","4+","0.5-","0","Web","","https://www.brainpop.com/games/windsimulator/",,,true],
["Edu","Yes","Disaster Detector","Weather","Atomspheric measurements to predict disasters","5+","1","0","Flash","DisasterDetector","https://ssec.si.edu/disaster-detector",,,true],
["Edu","Yes","Hot Air Balloon","Physics","Buoyancy","3+","0.5-","0","Web","HotAirBalloon","https://www.brainpop.com/games/hotairballoon/",,,true],
["Edu","Yes","Magnethunt","Physics","Magnets and electromagnets","3+","0.75-","0","Web","MagnetHunt","https://www.brainpop.com/games/magnethunt/",,,true],
["Edu","Yes","The Electric Shocktopus","Physics","Magnets and magnetic fields","6+","0.5-","0/$6","exe","Shocktopus","http://testtubegames.com/shocktopus.html",,,true],
["Edu","Yes","Velocity Raptor","Physics","Relativity and near light speed travel","9+","1","0","Web","VelocityRaptor","http://testtubegames.com/velocityraptor.html",,,true],
["Edu","Yes","Odyssey: The Invention of Science","Physics","Heliocentric/Geocentric models and related physics","4-10","5","$15","exe","Odyssey","http://store.steampowered.com/app/558110/Odyssey__The_Next_Generation_Science_Game/",,,true],
["Edu","Yes","Particulars","Physics","Subatomic particle mechanics","9+","7","$6","exe","Particulars","http://store.steampowered.com/app/259470/Particulars/",,,true],
["Edu","Yes","Quantum Marble Maze","Physics","Quantum mechanics","9+","1","0",".jar","QuantumMarbleMaze","http://tropic.org.uk/~crispin/quantum/",,,true],
["Edu","Yes","Bond Breaker","Physics","Atoms bonding","7+","2","0","Unity Web GL","BondBreaker","http://testtubegames.com/bondbreaker.html",,,true],
["Edu","","One Man Band","Misc.","Very basic music mixing","0-4","0.25-","0","Flash","OneManBand","https://www.brainpop.com/games/onemanband/",,,true],
["Edu","Maybe","Carmen Sandiago","Geography","Cities, their location, and a very brief history","varies","varies","0","DOS","CarmenSandiago","https://classicreload.com/where-in-the-world-is-carmen-sandiego-deluxe-edition.html ",,,true],
["Edu","Yes","Do I Have A Right?","Government","Bill of rights (best of this series)","","","0","Web","","https://www.brainpop.com/games/doihavearight/",,,true],
["Edu","Maybe","Court Quest","Government","Government: Court system of the US","6+","0.25","0","Flash","CourtQuest","https://www.brainpop.com/games/courtquest/",,,true],
["Edu","No","Win The White House","Government","Ideals of the Democratic and Repubilcan parties","9+","0.5-","0","Web","WinWhiteHouse","https://www.brainpop.com/games/winthewhitehouse/",,,true],
["Edu","Maybe","Branches Of Power","Government","Pass a law through 3 branches of US federal government","4+","0.5-","0","Flash","BranchesOfPower","https://www.brainpop.com/games/branchesofpower/",,,true],
["Edu","NO!","Cast Your Vote","Government","Political personality test","0","0.25-","0","Flash","CastYourVote","https://www.brainpop.com/games/castyourvote/",,,true],
["Edu","Maybe","Executive Command","Government","Perform the duties of the president","3+","0.5-","0","Web","ExecutiveCommand","https://www.brainpop.com/games/executivecommand/",,,true],
["Edu","Yes","Immigration Nation","Government","Rules for immigrating to the US","3+","0.5-","0","Flash","ImmigrationNation","https://www.icivics.org/games/immigration-nation",,,true],
["Edu","No","We The Jury","Government","Act as a juror on a court case","","","0","Flash","","https://www.brainpop.com/games/wethejury/",,,true],
["Edu","Maybe","Argument Wars","History","Historic Supreme Court cases","","","0","Flash","","https://www.brainpop.com/games/argumentwars/",,,true],
["Edu","No","Activate","Government","Manage a social advocacy group","","","0","Flash","","https://www.brainpop.com/games/activate/",,,true],
["Edu","Maybe","Counties Work","Government","Bureaucracy","","","0","Web","","https://www.brainpop.com/games/countieswork/",,,true],
["Edu","Yes","People's Pie","Government","Federal Budget","","","0","Flash","PeoplesPie","https://www.brainpop.com/games/peoplespie/",,,true],
["Edu","Maybe","Represent Me","None!","Stereotyping ","","","0","Flash","","https://www.brainpop.com/games/representme/",,,true],
["HW","NO!","Dino School Series","Math","Random school adjacent quizes.","2+","2","0","Android","","https://play.google.com/store/apps/details?id=co.familyplay.dinograde5free",,,true],
["HW","NO!","_ Grade Learning Games Series","Many","Random games with quiz questions jamed in ","4+","2","0/$4","Android","SixthGradeLearningGames","https://play.google.com/store/apps/details?id=com.kevinbradford.games.sixthgrade",,,true],
["Edu","YES!","Sine Rider","Math","Graphing equations and equations graphs","6+","3","0","exe","","http://sineridergame.com/",,,true],
["Edu","No","Quations","Math","Just play Sine Rider","","1/4-","0","","","https://www.newgrounds.com/portal/view/680544",,,true],
["Edu","No","Supreme Decision","Government","How the Supreme court makes decisions","","","0","Flash","","https://www.brainpop.com/games/supremedecision/",,,true],
["Sim","No","Ostevera","Government","Infrastructure management","3+","0.5-","0","Web","Ostevera","https://ostevera.spongelab.com/game/index.cfm",,,true],
["Issue","No","This War Of Mine","Issue","The effects of war on civilians","","","$20","exe","","http://store.steampowered.com/app/282070/This_War_of_Mine/",,,true],
["Issue","Maybe","Invasion!!","Issue","Invasive species","","","0","Flash","","https://www.brainpop.com/games/invasion/",,,true],
["Issue","No","Sam And Nicole","Issue","Gay relationships","","","0","exe","","https://sigridsanglar.itch.io/sam-and-nicole-demo",,,true],
["Issue","No","Yaku International","Issue","Getting water in Africa","0+","0.5-","0","Web","YakuInternational","http://www.kongregate.com/games/MouseCity/yaku-international",,,true],
["Issue","Maybe","Super Energy Apocalypse","Issue","Waste managment and pollution","","1","0","","SuperEnergyApocalypse","http://www.newgrounds.com/portal/view/430963",,,true],
["Issue","No","Aquation","Issue","Vague idea of the world's drinkable water supply system.","0+","0.25-","0","Web","Aquation","http://ssec.si.edu/sites/default/files/games/Aquation/index.html",,,true],
["Vid","NO!","Operation Ebola!","Biology","Ebola Virus (slide show with terrible game at the end)","9+","<0.25","0","Web","Ebola","https://catlilli.itch.io/ebola",,,true],
["Vid","NO!","Space Simulator","Astro-Physics","Flight simulator for historical space flights.","4+","2?","$10","exe","SpaceSimulator","https://store.steampowered.com/app/529060/Space_Simulator/",,,true],
["Vid","No","Powers of Minus Ten","Biology","Zoom in on cells to see them at different magnifications","6+","<1","$2","IOS","POMT","http://powersofminusten.com/",,,true]];